version: "3.9"
services:
  tusd:
    image: tusproject/tusd:v1.10
    restart: unless-stopped
    entrypoint: sh
    command: -c 'tusd -verbose -s3-bucket $$S3_BUCKET -s3-endpoint $$S3_HOST --hooks-http $$HOOK_URL --hooks-enabled-events pre-create,pre-finish,post-finish'
    env_file:
      - _env/tusd.env
    networks:
      default:
        ipv4_address: 10.20.0.10
  nginx:
    image: zemkog/uploader-project-nginx:20230403
    restart: unless-stopped
    depends_on:
      - tusd
    networks:
      default:
        ipv4_address: 10.20.0.11
  oauth:
    image: zemkog/oauth-server:20230320
    restart: unless-stopped
    env_file:
      - _env/oauth.env
    working_dir: /app
    volumes:
      - ./oauth-keys:/app/var/keys
    networks:
      default:
        ipv4_address: 10.20.0.12
  oauth_postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file:
      - _env/oauth_postgres.env
    volumes:
      - oauth_postgres:/var/lib/postgresql/data:rw
    networks:
      default:
        ipv4_address: 10.20.0.13
  backend:
    image: zemkog/uploader-project-backend:20230403
    env_file:
      - _env/backend.env
    restart: unless-stopped
    working_dir: /app
    networks:
      default:
        ipv4_address: 10.20.0.14
  backend_postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file:
      - _env/backend_postgres.env
    volumes:
      - backend_postgres:/var/lib/postgresql/data:rw
    networks:
      default:
        ipv4_address: 10.20.0.15
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.20.0.0/16
          gateway: 10.20.0.1
volumes:
  oauth_postgres:
  backend_postgres:
